protocol = "labjack-sensor"
doc = ""
traits = ["has-measure-trigger", "is-sensor", "is-daemon"]
hardware = ["labjack:t7-pro"]

[links]
source = "https://github.com/yaq-project/yaqd-labjack"
bugtracker = "https://github.com/yaq-project/yaqd-labjack/-/issues"
example-configs = "https://github.com/yaq-project/yaqd-labjack/tree/main/example-yaq-configs/labjack-sensor"

[installation]
PyPI = "https://pypi.org/project/yaqd-labjack"

[[types]]
type = "enum"
name = "feature"
symbols = ["none",
           "offset_and_slope",
	   "max_min_avg",
	   "resistance",
	   "average_and_threshold",
	   "rms_flex",
	   "flex_rms",
	   "thermocouple_type_e",
	   "thermocouple_type_j",
	   "thermocouple_type_k",
	   "thermocouple_type_r",
	   "thermocouple_type_t",
	   "thermocouple_type_s",
	   "thermocouple_type_n",
	   "thermocouple_type_b",
	   "thermocouple_type_c",
	   "rtd_pt100",
	   "rtd_pt500",
	   "rtd_pt1000",
	   "thermistor_steinhart_hart",
	   "thermistor_beta"]

[[types]]
type = "record"
name = "channel"
fields = [{"name"="modbus_address", "type"="int"},
          {"name"="enabled", "type"="boolean", "default"=true},
          {"name"="range", "type"="float"},
	  {"name"="differential", "type"="boolean", "default"=true},
	  {"name"="extended_feature", "type"="feature", "default"="none"}]

[config]

[config.channels]
type = "map"
values = "channel"
default = {}

[config.address]
type = "string"
default = "192.168.1.207"

[config.read_device_temperature]
doc = "If true, an additional channel device_temperature with units kelvin will be added."
type = "boolean"
default = true

[state]

[messages]
